# Generated by Django 5.1.7 on 2026-03-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('domain', models.CharField(help_text='Например: prava.be', max_length=200, verbose_name='Домен')),
                ('platform', models.CharField(choices=[('django', 'Django'), ('wordpress', 'WordPress'), ('nextjs', 'Next.js'), ('nuxt', 'Nuxt.js'), ('shopify', 'Shopify'), ('hugo', 'Hugo'), ('jekyll', 'Jekyll'), ('laravel', 'Laravel'), ('other', 'Other')], default='other', max_length=20, verbose_name='Платформа')),
                ('sitemap_url', models.URLField(blank=True, help_text='Например: https://prava.be/sitemap.xml', verbose_name='Sitemap URL')),
                ('search_console_property', models.CharField(blank=True, help_text='Например: sc-domain:prava.be', max_length=300, verbose_name='GSC Property')),
                ('analytics_property', models.CharField(blank=True, help_text='Например: 123456789', max_length=100, verbose_name='GA4 Property ID')),
                ('local_repo_path', models.CharField(blank=True, help_text='Например: /Users/user/projects/prava', max_length=500, verbose_name='Путь к локальному репозиторию')),
                ('git_remote_url', models.CharField(blank=True, help_text='Например: git@github.com:user/prava.git', max_length=500, verbose_name='Git Remote URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['name'],
            },
        ),
    ]
