# Generated by Django 6.0.3 on 2026-03-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_url',
            field=models.URLField(blank=True, help_text='Например: https://prava.be/admin/ или https://clikme.ru/admin/index.php', max_length=500, verbose_name='URL Admin панели'),
        ),
    ]
