# Generated by Django 6.0.3 on 2026-03-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('low_ctr', 'Низкий CTR'), ('low_position', 'Низкая позиция'), ('no_clicks', 'Нет кликов')], max_length=20, verbose_name='Тип')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('query', models.CharField(blank=True, max_length=500, verbose_name='Запрос')),
                ('page', models.URLField(blank=True, max_length=1000, verbose_name='Страница')),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0, verbose_name='CTR %')),
                ('position', models.FloatField(default=0.0, verbose_name='Позиция')),
                ('potential_clicks', models.IntegerField(default=0, verbose_name='Потенциал (клики)')),
                ('detected_at', models.DateField(auto_now_add=True, verbose_name='Дата обнаружения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_issues', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'SEO Проблема',
                'verbose_name_plural': 'SEO Проблемы',
                'ordering': ['-potential_clicks'],
                'indexes': [models.Index(fields=['project', 'issue_type'], name='seo_seoissu_project_1febc9_idx'), models.Index(fields=['project', 'priority'], name='seo_seoissu_project_7ba5cc_idx')],
            },
        ),
    ]
