# Generated by Django 6.0.3 on 2026-03-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoissue',
            name='note',
            field=models.TextField(blank=True, verbose_name='Заметка'),
        ),
        migrations.AddField(
            model_name='seoissue',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('important', 'Важно'), ('in_progress', 'В работе'), ('fixed', 'Исправлено'), ('ignored', 'Игнорировать')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='seoissue',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
