# Generated by Django 6.0.3 on 2026-03-18 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('rec_type', models.CharField(choices=[('title', 'Title'), ('description', 'Meta Description'), ('h1', 'H1'), ('ctr_analysis', 'CTR Analysis')], max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='projects.project')),
            ],
            options={
                'verbose_name': 'AI Рекомендация',
                'verbose_name_plural': 'AI Рекомендации',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'url'], name='ai_airecomm_project_82b925_idx'), models.Index(fields=['project', 'rec_type'], name='ai_airecomm_project_805159_idx')],
            },
        ),
    ]
