# Generated by Django 6.0.3 on 2026-03-17 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConsoleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('query', models.CharField(blank=True, max_length=500, verbose_name='Запрос')),
                ('page', models.URLField(blank=True, max_length=1000, verbose_name='Страница')),
                ('clicks', models.IntegerField(default=0, verbose_name='Клики')),
                ('impressions', models.IntegerField(default=0, verbose_name='Показы')),
                ('ctr', models.FloatField(default=0.0, verbose_name='CTR')),
                ('position', models.FloatField(default=0.0, verbose_name='Позиция')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_metrics', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'GSC Метрика',
                'verbose_name_plural': 'GSC Метрики',
                'ordering': ['-date', 'position'],
                'indexes': [models.Index(fields=['project', 'date'], name='analytics_s_project_4fa414_idx'), models.Index(fields=['project', 'query'], name='analytics_s_project_e051d5_idx'), models.Index(fields=['project', 'page'], name='analytics_s_project_68c150_idx')],
                'unique_together': {('project', 'date', 'query', 'page')},
            },
        ),
    ]
