# Generated by Django 6.0.3 on 2026-03-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('sessions', models.IntegerField(default=0, verbose_name='Сессии')),
                ('users', models.IntegerField(default=0, verbose_name='Пользователи')),
                ('new_users', models.IntegerField(default=0, verbose_name='Новые пользователи')),
                ('pageviews', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('bounce_rate', models.FloatField(default=0.0, verbose_name='Отказы (%)')),
                ('avg_session_duration', models.FloatField(default=0.0, verbose_name='Ср. время сессии (сек)')),
                ('channel', models.CharField(blank=True, default='', max_length=100, verbose_name='Канал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_metrics', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'GA4 Метрика',
                'verbose_name_plural': 'GA4 Метрики',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['project', 'date'], name='analytics_g_project_71b983_idx'), models.Index(fields=['project', 'channel'], name='analytics_g_project_75dfb2_idx')],
                'unique_together': {('project', 'date', 'channel')},
            },
        ),
    ]
