# Generated by Django 6.0.3 on 2026-03-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'В процессе'), ('done', 'Завершён'), ('error', 'Ошибка')], default='running', max_length=10)),
                ('pages_found', models.PositiveIntegerField(default=0)),
                ('pages_crawled', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_sessions', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('meta_description', models.TextField(blank=True)),
                ('h1', models.CharField(blank=True, max_length=512)),
                ('canonical', models.URLField(blank=True, max_length=2048)),
                ('load_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('images_missing_alt', models.PositiveSmallIntegerField(default=0)),
                ('internal_links', models.PositiveSmallIntegerField(default=0)),
                ('issue_title_missing', models.BooleanField(default=False)),
                ('issue_title_short', models.BooleanField(default=False)),
                ('issue_title_long', models.BooleanField(default=False)),
                ('issue_desc_missing', models.BooleanField(default=False)),
                ('issue_desc_short', models.BooleanField(default=False)),
                ('issue_desc_long', models.BooleanField(default=False)),
                ('issue_h1_missing', models.BooleanField(default=False)),
                ('issue_h1_multiple', models.BooleanField(default=False)),
                ('issue_canonical_diff', models.BooleanField(default=False)),
                ('issue_broken', models.BooleanField(default=False)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_results', to='projects.project')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='crawler.crawlsession')),
            ],
            options={
                'ordering': ['url'],
                'unique_together': {('session', 'url')},
            },
        ),
    ]
