# Generated by Django 6.0.3 on 2026-03-18 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broken_url', models.URLField(max_length=2048)),
                ('found_on', models.URLField(max_length=2048)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anchor_text', models.CharField(blank=True, max_length=512)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broken_links', to='crawler.crawlsession')),
            ],
            options={
                'ordering': ['broken_url'],
                'unique_together': {('session', 'broken_url', 'found_on')},
            },
        ),
    ]
