# Generated by Django 6.0.3 on 2026-03-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_brokenlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlsession',
            name='mode',
            field=models.CharField(choices=[('links', 'Обход по ссылкам'), ('sitemap', 'По sitemap.xml')], default='links', max_length=10),
        ),
    ]
